### ISSUE TITLE
ErrorException in Userstamps.php line 117

### ISSUE THREAD

**Issue by dsnoeck** [WildSideUK/Laravel-Userstamps#6]
Hi,

I'm using https://github.com/sroutier/laravel-enterprise-starter-kit as base for my webapp.

It works well and save the user ID in the DB when I'm saving or updating a model. But it fails when I want to display the user in my view with ```$model -> creator;```

```
ErrorException in Userstamps.php line 117:
Call to undefined method Illuminate\Auth\Guard::guard()
```

Any idea what could be the cause ?

**Comment by mattmcdonald-uk** [comment]
This should be fixed in most recent release.

**Comment by dsnoeck** [comment]
Thanks, but it is still not ok. the method getProvider() from \Illuminate\Auth\Guard return a userProvider object which doesn't has the method getModel(): 

https://laravel.com/api/5.1/Illuminate/Auth/Guard.html#method_getProvider

**Comment by mattmcdonald-uk** [comment]
I believe this is specific to the custom user provider you're using.

In a standard Laravel 5.1 installation the method works fine.

I'd recommend you implement the creator and updater methods manually on each of your models using this trait. That would override the one provided by the trait and allow you to write custom logic that works with the specific provider you're using.
